### ISSUE TITLE
Error "FATAL: Failed to open a temp file for chrom lengths"

### ISSUE THREAD

**Issue by haowuisu** [MikeAxtell/butter#9]
I got an issue at the third step of bam2wig, and the program failed to open the temp file "chr_lens_temp.txt". 

I have installed wigtobigwig. My BAM file has been sorted and indexed. The header is as follows,

$ samtools view -H PB_ATAC_T2.filtered.bam
@HD     VN:1.5  SO:coordinate
@SQ     SN:1    LN:307041717
@SQ     SN:2    LN:244442276
@SQ     SN:3    LN:235667834
@SQ     SN:4    LN:246994605
@SQ     SN:5    LN:223902240
@SQ     SN:6    LN:174033170
@SQ     SN:7    LN:182381542
@SQ     SN:8    LN:181122637
@SQ     SN:9    LN:159769782
@SQ     SN:10   LN:150982314
@SQ     SN:Pt   LN:140384
@SQ     SN:Mt   LN:569630
....

Why did the error occur? How to fix it? 

Thanks.

**Comment by MikeAxtell** [comment]
Sorry, but butter has been abandoned for some time. For the same general spirit of sRNA-seq alignments with awareness of multi-mapping reads, use the current version of ShortStack (https://github.com/MikeAxtell/ShortStack) instead.



Michael J. Axtell, Ph.D.
Professor of Biology
The Pennsylvania State University
https://sites.psu.edu/axtell
https://plantsmallrnagenes.science.psu.edu

**Comment by haowuisu** [comment]
Sorry, maybe I reported the issue at a wrong place.

I was using bam2wig (not butter), and at the phase three “Phase Three: Writing bigwig file”, I’ve got the error message “FATAL: Failed to open a temp file for chrom lengths”, and failed to create the bigwig file.

I was trying to convert BAM file to BigWig file, and I have already installed and loaded package wigToBigWig. Could you help me with this? Thanks.

________________________
Hao Wu
Postdoctoral Research Associate
Becraft Lab
Department of Genetics, Development and Cell Biology
Iowa State University
